# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# compile CXX with /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CXX_FLAGS = -fvisibility=hidden  -Wall -Wextra -std=c++14 -flto=thin -stdlib=libc++ -O3 -DNDEBUG   -fobjc-arc

CXX_DEFINES = -DCORO_SJLJ -DGLAD_GLAPI_EXPORT -DNANOGUI_PYTHON -DNANOGUI_SHARED -DNVG_SHARED

CXX_INCLUDES = -I/Users/chris/mfm/nanogui/ext/eigen -I/Users/chris/mfm/nanogui/ext/glfw/include -I/Users/chris/mfm/nanogui/ext/nanovg/src -I/Users/chris/mfm/nanogui/include -I/Users/chris/mfm/nanogui/build -I/Users/chris/mfm/nanogui/ext/coro -I/Users/chris/mfm/nanogui/ext/pybind11/include -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m 

