# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/chris/mfm/code/libigl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/chris/mfm/code/libigl/build

# Include any dependencies generated for this target.
include tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/depend.make

# Include the progress variables for this target.
include tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/progress.make

# Include the compile flags for this target's objects.
include tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/flags.make

tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o: tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/flags.make
tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o: ../tutorial/102_DrawMesh/main.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/chris/mfm/code/libigl/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o"
	cd /Users/chris/mfm/code/libigl/build/tutorial/102_DrawMesh && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o -c /Users/chris/mfm/code/libigl/tutorial/102_DrawMesh/main.cpp

tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/102_DrawMesh_bin.dir/main.cpp.i"
	cd /Users/chris/mfm/code/libigl/build/tutorial/102_DrawMesh && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/chris/mfm/code/libigl/tutorial/102_DrawMesh/main.cpp > CMakeFiles/102_DrawMesh_bin.dir/main.cpp.i

tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/102_DrawMesh_bin.dir/main.cpp.s"
	cd /Users/chris/mfm/code/libigl/build/tutorial/102_DrawMesh && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/chris/mfm/code/libigl/tutorial/102_DrawMesh/main.cpp -o CMakeFiles/102_DrawMesh_bin.dir/main.cpp.s

tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o.requires:

.PHONY : tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o.requires

tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o.provides: tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o.requires
	$(MAKE) -f tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/build.make tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o.provides.build
.PHONY : tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o.provides

tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o.provides.build: tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o


# Object files for target 102_DrawMesh_bin
102_DrawMesh_bin_OBJECTS = \
"CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o"

# External object files for target 102_DrawMesh_bin
102_DrawMesh_bin_EXTERNAL_OBJECTS =

tutorial/102_DrawMesh_bin: tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o
tutorial/102_DrawMesh_bin: tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/build.make
tutorial/102_DrawMesh_bin: libigl.a
tutorial/102_DrawMesh_bin: libigl_opengl.a
tutorial/102_DrawMesh_bin: libigl_opengl_glfw.a
tutorial/102_DrawMesh_bin: libigl_opengl.a
tutorial/102_DrawMesh_bin: libigl.a
tutorial/102_DrawMesh_bin: /System/Library/Frameworks/OpenGL.framework/OpenGL.tbd
tutorial/102_DrawMesh_bin: libglad.a
tutorial/102_DrawMesh_bin: libglfw3.a
tutorial/102_DrawMesh_bin: tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/Users/chris/mfm/code/libigl/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX executable ../102_DrawMesh_bin"
	cd /Users/chris/mfm/code/libigl/build/tutorial/102_DrawMesh && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/102_DrawMesh_bin.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/build: tutorial/102_DrawMesh_bin

.PHONY : tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/build

tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/requires: tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o.requires

.PHONY : tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/requires

tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/clean:
	cd /Users/chris/mfm/code/libigl/build/tutorial/102_DrawMesh && $(CMAKE_COMMAND) -P CMakeFiles/102_DrawMesh_bin.dir/cmake_clean.cmake
.PHONY : tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/clean

tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/depend:
	cd /Users/chris/mfm/code/libigl/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /Users/chris/mfm/code/libigl /Users/chris/mfm/code/libigl/tutorial/102_DrawMesh /Users/chris/mfm/code/libigl/build /Users/chris/mfm/code/libigl/build/tutorial/102_DrawMesh /Users/chris/mfm/code/libigl/build/tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : tutorial/102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/depend

