# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# compile CXX with /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CXX_FLAGS =  -fPIC -O3 -DNDEBUG   -std=gnu++11

CXX_DEFINES = -DIGL_STATIC_LIBRARY -DTUTORIAL_SHARED_PATH=\"/Users/chris/mfm/code/libigl/cmake/../external/../tutorial/data\"

CXX_INCLUDES = -isystem /Users/chris/mfm/code/libigl/cmake/../include -isystem /Users/chris/mfm/code/libigl/cmake/../external/eigen -I/Users/chris/mfm/code/libigl/external/glad/include -I/Users/chris/mfm/code/libigl/external/glfw/include -I/Users/chris/mfm/code/libigl/tutorial 

